# Pandas

Pandas is a powerful python library for working with structured data, enabling tasks like importing, cleansing, transforming and analyzing datasets efficiently and make conclusions based on statistical theories.

- **Series**: A Series is a one-dimensional labeled array that can hold any data type (integer, string, float, Python objects, etc.).
- **Data Frames**: A Data Frame is a 2-dimensional tabular data structure with labeled axes (rows and columns). A DataFrame object is similar to a spreadsheet or a database table.
- **Panel (Deprecated)**: A Panel is a 3-dimensional data structure, similar to a DataFrame, but with three dimensions (rows, columns, and pages).
- **Index**: An Index object is a one-dimensional array that can hold any type of data (integer, string, float, Python objects, etc.).
- **MultiIndex**: A MultiIndex object is a hierarchical index, similar to an Index, but with multiple levels.
- **Categorical**: A Categorical object is a type of Index that represents categorical data.
- **DatetimeIndex**: A DatetimeIndex object is a type of Index that represents datetime data.
- **TimedeltaIndex**: A TimedeltaIndex object is a type of Index that represents timedelta data.
- **IntervalIndex**: An IntervalIndex object is a type of Index that represents interval data.
- **Sparse**: A Sparse object is a sparse representation of a data structure, such as a DataFrame or Series.
- **Panel4D**: A Panel4D object is a 4-dimensional data structure, similar to a Panel, but with four dimensions (rows, columns, pages, and sections).

In [2]:
import pandas as pd

## Series

In [3]:
# Create a Series
s = pd.Series([1, 2, 3, 4, 5])
print(s.values)  # Print the values of the Series.
print('Mean:', s.mean())  # Calculate the mean of the Series.
print('Median:', s.median())  # Calculate the median of the Series.
print('Mode:', s.mode())  # Calculate the mode of the Series.
print('Standard Deviation:', s.std())  # Calculate the standard deviation of the Series.
print('Variance:', s.var())  # Calculate the variance of the Series.

[1 2 3 4 5]
Mean: 3.0
Median: 3.0
Mode: 0    1
1    2
2    3
3    4
4    5
dtype: int64
Standard Deviation: 1.5811388300841898
Variance: 2.5


## DataFrame

In [4]:
# DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
df = pd.DataFrame(data)
print(df)  # Print the DataFrame.
print(df['Name'])  # Access the 'Name' column.
print(df['Age'].mean())  # Calculate the mean age.
print(df['City'].unique())  # Get unique cities.
print(df.describe())  # Get summary statistics for the DataFrame.
print(df[df['Age'] > 30])  # Filter rows where age is greater than 30.
print(df.sort_values(by='Age'))  # Sort the DataFrame by age.
print(df.groupby('City')['Age'].mean())  # Group by city and calculate mean age.
print(df.isnull().sum())  # Check for missing values in the DataFrame.
print(df['Age'].fillna(df['Age'].mean()))  # Fill missing values in 'Age' with the mean age.
print(df['City'].value_counts())  # Count the occurrences of each city.
print(df['Age'].apply(lambda x: 'Adult' if x >= 18 else 'Minor'))  # Apply a function to the 'Age' column.
print(df['Name'].str.upper())  # Convert the 'Name' column to uppercase.
print(df['City'].str.contains('New'))  # Check if 'City' contains 'New'.
# Ensure correlation is computed only on numeric columns (avoid converting string columns like 'Name' to float)
print(df.corr(numeric_only=True))  # Calculate the correlation between numeric columns in the DataFrame.


      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix
0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: str
35.0
<StringArray>
['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
Length: 5, dtype: str
             Age
count   5.000000
mean   35.000000
std     7.905694
min    25.000000
25%    30.000000
50%    35.000000
75%    40.000000
max    45.000000
      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston
4      Eve   45  Phoenix
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix
City
Chicago        35.0
Houston        40.0
Los Angeles    30.0
New York       25.0
Phoenix        45.0
Name: Age, dtype: float64
Name    0
Age     0
City    0
dtype: int64
0    25
1    30
2    35
3    40
4  

## Index

In [7]:
# Create a Index
index = pd.Index(['a', 'b', 'c', 'd', 'e'])
print(index)  # Print the Index.
print(index[0])  # Access the first element of the Index.
print(index[1:4])  # Access a slice of the Index.
print(index.append(pd.Index(['f', 'g'])))  # Append another Index to the current Index.
print(index.intersection(pd.Index(['b', 'c', 'f'])))  # Find the intersection of the current Index with another Index.
print(index.difference(pd.Index(['b', 'c'])))  # Find the difference between the current Index and another Index.
print(index.union(pd.Index(['f', 'g'])))  # Find the union of the current Index with another Index.
print(index.isin(['a', 'e', 'f']))  # Check if elements of the Index are in a list of values.
print(index.delete(2))  # Delete the element at index position 2.
print(index.insert(2, 'x'))  # Insert a new element 'x' at index position 2.
print(index.rename('MyIndex'))  # Rename the Index.
print(index.to_list())  # Convert the Index to a list.
print(index.to_series())  # Convert the Index to a Series.
print(index.to_frame())  # Convert the Index to a DataFrame.
print(index.value_counts())  # Count the occurrences of each unique value in the Index.
print(index.nunique())  # Count the number of unique values in the Index.
print(index.is_unique)  # Check if all values in the Index are unique.
print(index.is_monotonic_increasing or index.is_monotonic_decreasing)  # Check if the Index is monotonic (sorted).
print(index.is_monotonic_increasing)  # Check if the Index is monotonically increasing.
print(index.is_monotonic_decreasing)  # Check if the Index is monotonically decreasing
print(index.has_duplicates)  # Check if the Index has duplicate values.
print(index.isin(['a', 'b', 'c']))  # Check if elements of the Index are in a list of values.
print(index.get_loc('c'))  # Get the location of the element 'c' in the Index.
print(index.get_indexer(['a', 'c', 'e']))  # Get the indexer for a list of values in the Index.
print(index.get_indexer_for(['a', 'c', 'e']))  # Get the indexer for a list of values in the Index.
print(index.get_indexer_non_unique(['a', 'c', 'e']))  # Get the indexer for a list of values in the Index, including non-unique values.


Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
a
Index(['b', 'c', 'd'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')
Index(['b', 'c'], dtype='str')
Index(['a', 'd', 'e'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')
[ True False False False  True]
Index(['a', 'b', 'd', 'e'], dtype='str')
Index(['a', 'b', 'x', 'c', 'd', 'e'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e'], dtype='str', name='MyIndex')
['a', 'b', 'c', 'd', 'e']
a    a
b    b
c    c
d    d
e    e
dtype: str
   0
a  a
b  b
c  c
d  d
e  e
a    1
b    1
c    1
d    1
e    1
Name: count, dtype: int64
5
True
True
True
False
False
[ True  True  True False False]
2
[0 2 4]
[0 2 4]
(array([0, 2, 4]), array([], dtype=int64))


## MultiIndex

In [9]:
# Create a MultiIndex
arrays = [['A', 'A', 'B', 'B'], ['one', 'two', 'one', 'two']]
multi_index = pd.MultiIndex.from_arrays(arrays, names=['Letter', 'Number'])
print(multi_index)  # Print the MultiIndex.
print(multi_index[0])  # Access the first element of the MultiIndex.
print(multi_index[1:3])  # Access a slice of the MultiIndex.
print(multi_index.get_level_values('Letter'))  # Get the values of the 'Letter
print(multi_index.get_level_values('Number'))  # Get the values of the 'Number' level.
print(multi_index.to_frame())  # Convert the MultiIndex to a DataFrame.
print(multi_index.to_series())  # Convert the MultiIndex to a Series.
print(multi_index.isin([('A', 'one'), ('B', 'two')]))  # Check if tuples are in the MultiIndex.
print(multi_index.get_loc(('A', 'one')))  # Get the location of the tuple ('A', 'one') in

MultiIndex([('A', 'one'),
            ('A', 'two'),
            ('B', 'one'),
            ('B', 'two')],
           names=['Letter', 'Number'])
('A', 'one')
MultiIndex([('A', 'two'),
            ('B', 'one')],
           names=['Letter', 'Number'])
Index(['A', 'A', 'B', 'B'], dtype='str', name='Letter')
Index(['one', 'two', 'one', 'two'], dtype='str', name='Number')
              Letter Number
Letter Number              
A      one         A    one
       two         A    two
B      one         B    one
       two         B    two
Letter  Number
A       one       (A, one)
        two       (A, two)
B       one       (B, one)
        two       (B, two)
dtype: object
[ True False False  True]
0


# Categorical

In [12]:
# Categorical data
categories = pd.Categorical(['apple', 'banana', 'apple', 'orange', 'banana'])
print(categories)  # Print the Categorical data.
print(categories.categories)  # Print the categories.
print(categories.codes)  # Print the codes for the Categorical data.
print(categories.value_counts())  # Count the occurrences of each category.
print(categories.describe())  # Get summary statistics for the Categorical data.
print(categories.isnull())  # Check for missing values in the Categorical data.
print(categories.notnull())  # Check for non-missing values in the Categorical data.
print(categories.astype('object'))  # Convert the Categorical data to an object type.
print(categories.astype('str'))  # Convert the Categorical data to a string type.
print(categories.astype('category'))  # Convert the Categorical data to a category type (no change).
print(categories.add_categories(['grape']))  # Add a new category 'grape' to the Categorical data.
print(categories.remove_categories(['banana']))  # Remove the category 'banana' from the Categorical data.
print(categories.rename_categories({'apple': 'fruit', 'orange': 'citrus'}))  # Rename categories in the Categorical data.
print(categories.set_categories(['fruit', 'citrus', 'grape'], ordered=True))  # Set new categories and order for the Categorical data.
print(categories.as_ordered())  # Set the Categorical data as ordered.
print(categories.as_unordered())  # Set the Categorical data as unordered.
print(categories.ordered)  # Check if the Categorical data is ordered.
print(categories.unique)  # Check the unique values in the Categorical data.

['apple', 'banana', 'apple', 'orange', 'banana']
Categories (3, str): ['apple', 'banana', 'orange']
Index(['apple', 'banana', 'orange'], dtype='str')
[0 1 0 2 1]
apple     2
banana    2
orange    1
Name: count, dtype: int64
            counts  freqs
categories               
apple            2    0.4
banana           2    0.4
orange           1    0.2
[False False False False False]
[ True  True  True  True  True]
['apple' 'banana' 'apple' 'orange' 'banana']
<StringArray>
['apple', 'banana', 'apple', 'orange', 'banana']
Length: 5, dtype: str
['apple', 'banana', 'apple', 'orange', 'banana']
Categories (3, str): ['apple', 'banana', 'orange']
['apple', 'banana', 'apple', 'orange', 'banana']
Categories (4, str): ['apple', 'banana', 'orange', 'grape']
['apple', NaN, 'apple', 'orange', NaN]
Categories (2, str): ['apple', 'orange']
['fruit', 'banana', 'fruit', 'citrus', 'banana']
Categories (3, str): ['fruit', 'banana', 'citrus']
[NaN, NaN, NaN, NaN, NaN]
Categories (3, str): ['fruit' < 'citr

## DatetimeIndex

In [16]:
# DatetimeIndex
dates = pd.date_range('2024-01-01', periods=5, freq='D')
print(dates)  # Print the DatetimeIndex.
print(dates.year)  # Access the year component of the DatetimeIndex.
print(dates.month)  # Access the month component of the DatetimeIndex.
print(dates.day)  # Access the day component of the DatetimeIndex.
print(dates.weekday)  # Access the weekday component of the DatetimeIndex (0=Monday, 6=Sunday).
print(dates.dayofweek)  # Access the day of the week component of the DatetimeIndex (0=Monday, 6=Sunday).
print(dates.dayofyear)  # Access the day of the year component of the DatetimeIndex (1-366).
print(dates.is_month_start)  # Check if each date is the start of the month.
print(dates.is_month_end)  # Check if each date is the end of the month.
print(dates.is_quarter_start)  # Check if each date is the start of the quarter.
print(dates.is_quarter_end)  # Check if each date is the end of the quarter.
print(dates.is_year_start)  # Check if each date is the start of the year.
print(dates.is_year_end)  # Check if each date is the end of the year.
print(dates.to_period('M'))  # Convert the DatetimeIndex to a PeriodIndex with monthly frequency.
print(dates.to_period('Q'))  # Convert the DatetimeIndex to a PeriodIndex with quarterly frequency.
print(dates.to_period('Y'))  # Convert the DatetimeIndex to a PeriodIndex with annual frequency.
print(dates.to_julian_date())  # Convert the DatetimeIndex to Julian dates.
print(dates.to_pydatetime())  # Convert the DatetimeIndex to an array of Python datetime objects.
print(dates.to_numpy())  # Convert the DatetimeIndex to a NumPy array of datetime64 objects.
print(dates.to_series())  # Convert the DatetimeIndex to a Series of Timestamps.
print(dates.to_frame())  # Convert the DatetimeIndex to a DataFrame with a single column of Timestamps.
print(dates.isin(pd.date_range('2024-01-02', '2024-01-04')))  # Check if dates are in a specified date range.
print(dates.get_loc('2024-01-03'))  # Get the location of a specific date in the DatetimeIndex.
print(dates.get_indexer(pd.date_range('2024-01-02', '2024-01-04')))  # Get the indexer for a specified date range in the DatetimeIndex.
print(dates.get_indexer_for(pd.date_range('2024-01-02', '2024-01-04')))  # Get the indexer for a specified date range in the DatetimeIndex, including non-unique values.
print(dates.get_indexer_non_unique(pd.date_range('2024-01-02', '2024-01-04')))  # Get the indexer for a specified date

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05'],
              dtype='datetime64[us]', freq='D')
Index([2024, 2024, 2024, 2024, 2024], dtype='int32')
Index([1, 1, 1, 1, 1], dtype='int32')
Index([1, 2, 3, 4, 5], dtype='int32')
Index([0, 1, 2, 3, 4], dtype='int32')
Index([0, 1, 2, 3, 4], dtype='int32')
Index([1, 2, 3, 4, 5], dtype='int32')
[ True False False False False]
[False False False False False]
[ True False False False False]
[False False False False False]
[ True False False False False]
[False False False False False]
PeriodIndex(['2024-01', '2024-01', '2024-01', '2024-01', '2024-01'], dtype='period[M]')
PeriodIndex(['2024Q1', '2024Q1', '2024Q1', '2024Q1', '2024Q1'], dtype='period[Q-DEC]')
PeriodIndex(['2024', '2024', '2024', '2024', '2024'], dtype='period[Y-DEC]')
Index([2460310.5, 2460311.5, 2460312.5, 2460313.5, 2460314.5], dtype='float64')
[datetime.datetime(2024, 1, 1, 0, 0) datetime.datetime(2024, 1, 2, 0, 0)
 datetime.d

## TimedeltaIndex

In [19]:
## TimedeltaIndex
timedeltas = pd.to_timedelta(['1 day', '2 days', '3 days', '4 days', '5 days'])
print(timedeltas)  # Print the TimedeltaIndex.
print(timedeltas.days)  # Access the days component of the TimedeltaIndex.
print(timedeltas.total_seconds())  # Access the total seconds component of the TimedeltaIndex.
print(timedeltas.components)  # Access the components (days, hours, minutes, seconds) of the TimedeltaIndex.
print(timedeltas.to_pytimedelta())  # Convert the TimedeltaIndex to an array of Python timedelta objects.
print(timedeltas.to_numpy())  # Convert the TimedeltaIndex to a NumPy array of timedelta64 objects.
print(timedeltas.to_series())  # Convert the TimedeltaIndex to a Series of Timedelta objects.
print(timedeltas.to_frame())  # Convert the TimedeltaIndex to a DataFrame with a single column of Timedelta objects.
print(timedeltas.isin(pd.to_timedelta(['2 days', '4 days'])))  # Check if timedeltas are in a specified list of timedeltas.
print(timedeltas.get_loc(pd.to_timedelta('3 days')))  # Get the location of a specific timedelta in the TimedeltaIndex.
print(timedeltas.get_indexer(pd.to_timedelta(['2 days', '4 days'])))  # Get the indexer for a specified list of timedeltas in the TimedeltaIndex.
print(timedeltas.get_indexer_for(pd.to_timedelta(['2 days', '4 days'])))  # Get the indexer for a specified list of timedeltas in the TimedeltaIndex, including non-unique values.
print(timedeltas.get_indexer_non_unique(pd.to_timedelta(['2 days', '4 days'])))  # Get the indexer for a specified list of timedeltas in the TimedeltaIndex, including non-unique values.

TimedeltaIndex(['1 days', '2 days', '3 days', '4 days', '5 days'], dtype='timedelta64[us]', freq=None)
Index([1, 2, 3, 4, 5], dtype='int64')
Index([86400.0, 172800.0, 259200.0, 345600.0, 432000.0], dtype='float64')
   days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds
0     1      0        0        0             0             0            0
1     2      0        0        0             0             0            0
2     3      0        0        0             0             0            0
3     4      0        0        0             0             0            0
4     5      0        0        0             0             0            0
[datetime.timedelta(days=1) datetime.timedelta(days=2)
 datetime.timedelta(days=3) datetime.timedelta(days=4)
 datetime.timedelta(days=5)]
[ 86400000000 172800000000 259200000000 345600000000 432000000000]
1 days   1 days
2 days   2 days
3 days   3 days
4 days   4 days
5 days   5 days
dtype: timedelta64[us]
            0
1 days 1 days
2 da

## IntervalIndex

In [20]:
# IntervalIndex
intervals = pd.IntervalIndex.from_tuples([(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)])
print(intervals)  # Print the IntervalIndex.
print(intervals.left)  # Access the left endpoints of the intervals.
print(intervals.right)  # Access the right endpoints of the intervals.
print(intervals.closed)  # Access the closed attribute of the intervals (whether they are closed on the left, right, both, or neither).
print(intervals.to_series())  # Convert the IntervalIndex to a Series of Interval objects.
print(intervals.to_frame())  # Convert the IntervalIndex to a DataFrame with two columns for the left and right endpoints of the intervals.
print(intervals.isin([pd.Interval(1, 2), pd.Interval(3, 4)]))  # Check if specific intervals are in the IntervalIndex.
print(intervals.get_loc(pd.Interval(2, 3)))  # Get the location of a specific interval in the IntervalIndex.
print(intervals.get_indexer(pd.IntervalIndex([pd.Interval(1, 2), pd.Interval(3, 4)])))  # Get the indexer for a specified list of intervals in the IntervalIndex.
# Note: get_indexer_for and get_indexer_non_unique are not standard methods for IntervalIndex; removing them to avoid errors.

IntervalIndex([(0, 1], (1, 2], (2, 3], (3, 4], (4, 5]], dtype='interval[int64, right]')
Index([0, 1, 2, 3, 4], dtype='int64')
Index([1, 2, 3, 4, 5], dtype='int64')
right
(0, 1]    (0, 1]
(1, 2]    (1, 2]
(2, 3]    (2, 3]
(3, 4]    (3, 4]
(4, 5]    (4, 5]
dtype: interval
             0
(0, 1]  (0, 1]
(1, 2]  (1, 2]
(2, 3]  (2, 3]
(3, 4]  (3, 4]
(4, 5]  (4, 5]
[False  True False  True False]
2
[1 3]


## PeriodIndex

In [21]:
# PeriodIndex
periods = pd.period_range('2024-01', periods=5, freq='M')
print(periods)  # Print the PeriodIndex.
print(periods.year)  # Access the year component of the PeriodIndex.
print(periods.month)  # Access the month component of the PeriodIndex.
print(periods.day)  # Access the day component of the PeriodIndex (will be 1 for monthly frequency).
print(periods.quarter)  # Access the quarter component of the PeriodIndex.
print(periods.to_timestamp())  # Convert the PeriodIndex to a DatetimeIndex.
print(periods.to_timestamp(how='end'))  # Convert the PeriodIndex to a DatetimeIndex, using the end of the period.
print(periods.to_timestamp(how='start'))  # Convert the PeriodIndex to a DatetimeIndex, using the start of the period.
print(periods.to_timestamp(how='e'))  # Convert the PeriodIndex to a DatetimeIndex, using the end of the period.
print(periods.to_timestamp(how='s'))  # Convert the PeriodIndex to a DatetimeIndex, using the start of the period.
print(periods.to_series())  # Convert the PeriodIndex to a Series of Period objects.
print(periods.to_frame())  # Convert the PeriodIndex to a DataFrame with a single column of Period objects.
print(periods.isin(pd.period_range('2024-02', '2024-04', freq='M')))  # Check if periods are in a specified range of periods.
print(periods.get_loc(pd.Period('2024-03', freq='M')))  # Get the location of a specific period in the PeriodIndex.
print(periods.get_indexer(pd.period_range('2024-02', '2024-04', freq='M')))  # Get the indexer for a specified range of periods in the PeriodIndex.
print(periods.get_indexer_for(pd.period_range('2024-02', '2024-04', freq='M'))  # Get the indexer for a specified range of periods in the PeriodIndex, including non-unique values.
      )
print(periods.get_indexer_non_unique(pd.period_range('2024-02', '2024-04', freq='M'))  # Get the indexer for a specified range of periods in the PeriodIndex, including non-unique values.
      )

PeriodIndex(['2024-01', '2024-02', '2024-03', '2024-04', '2024-05'], dtype='period[M]')
Index([2024, 2024, 2024, 2024, 2024], dtype='int64')
Index([1, 2, 3, 4, 5], dtype='int64')
Index([31, 29, 31, 30, 31], dtype='int64')
Index([1, 1, 1, 2, 2], dtype='int64')
DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01'],
              dtype='datetime64[us]', freq='MS')
DatetimeIndex(['2024-01-31 23:59:59.999999', '2024-02-29 23:59:59.999999',
               '2024-03-31 23:59:59.999999', '2024-04-30 23:59:59.999999',
               '2024-05-31 23:59:59.999999'],
              dtype='datetime64[us]', freq=None)
DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01'],
              dtype='datetime64[us]', freq='MS')
DatetimeIndex(['2024-01-31 23:59:59.999999', '2024-02-29 23:59:59.999999',
               '2024-03-31 23:59:59.999999', '2024-04-30 23:59:59.999999',
               '2024-05-31 23:59:59.999999'],

## Sparse

In [25]:
%pip install scipy

# Sparse data
sparse_series = pd.Series([0, 0, 1, 0, 0], dtype='Sparse[int]')
print(sparse_series)  # Print the Sparse Series.
print(sparse_series.sparse)  # Access the sparse accessor of the Series.
print(sparse_series.sparse.density)  # Get the density of the sparse data (the proportion of non-zero entries).
print(sparse_series.sparse.npoints)  # Get the number of non-zero entries in the sparse data.
print(sparse_series.memory_usage())  # Get the memory usage of the sparse data in bytes.
print(sparse_series.sparse.to_dense())  # Convert the sparse Series to a dense Series.
# The following lines require scipy to be installed. If scipy is not available, these will raise ModuleNotFoundError.
# Uncomment and install scipy if needed: %pip install scipy
# print(sparse_series.sparse.to_coo())  # Convert the sparse Series to a COO sparse matrix.
# print(sparse_series.sparse.to_coo().toarray())  # Convert the sparse Series to a COO sparse matrix and then to a dense NumPy array.
# print(sparse_series.sparse.to_csr())  # Convert the sparse Series to a CSR sparse matrix.
# print(sparse_series.sparse.to_csr().toarray())  # Convert the sparse Series to a CSR sparse matrix and then to a dense NumPy array.
# print(sparse_series.sparse.to_csc())  # Convert the sparse Series to a CSC sparse matrix.
# print(sparse_series.sparse.to_csc().toarray())  # Convert the sparse Series to a CSC sparse matrix and then to a dense NumPy array.
# print(sparse_series.sparse.to_coo().tocsc())  # Convert the sparse Series to a COO sparse matrix and then to a CSC sparse matrix.
# print(sparse_series.sparse.to_coo().tocsc().toarray())  # Convert the sparse Series to a COO sparse matrix, then to a CSC sparse matrix, and finally to a dense NumPy array.
# print(sparse_series.sparse.to_coo().tocsr())  # Convert the sparse Series to a COO sparse matrix and then to a CSR sparse matrix.
# print(sparse_series.sparse.to_coo().tocsr().toarray())  # Convert the sparse Series to a COO sparse matrix, then to a CSR sparse matrix, and finally to a dense NumPy array.

/Users/skakumanu/practice/do-python/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
0    0
1    0
2    1
3    0
4    0
dtype: Sparse[int64, 0]
0.2
1
144
0    0
1    0
2    1
3    0
4    0
dtype: int64


## Panel4D

In [28]:
import numpy as np

# Panel4D is deprecated in pandas, using dict of numpy arrays instead
panel4d = {'A': np.random.randn(2, 2, 2, 2), 'B': np.random.randn(2, 2, 2, 2)}
print(panel4d)  # Print the dict.
print(panel4d['A'])  # Access a specific array in the dict.
print(panel4d['A'].shape)  # Get the shape of a specific array.
print(panel4d['A'].ndim)  # Get the number of dimensions of a specific array.
print(panel4d['A'].dtype)  # Get the data type of a specific array.
print(panel4d['A'])  # Get the values of a specific array (same as above).
# Skipping index, columns, items, major_axis, minor_axis as they are not applicable for numpy arrays
print(panel4d['A'].swapaxes(0, 1))  # Swap the axes of a specific array.
print(panel4d['A'].swapaxes(1, 2))  # Swap the axes of a specific array.
print(panel4d['A'].swapaxes(2, 3))  # Swap the axes of a specific array.
print(panel4d['A'].swapaxes(0, 2))  # Swap the axes of a specific array.
print(panel4d['A'].swapaxes(0, 3))  # Swap the axes of a specific array.
print(panel4d['A'].swapaxes(1, 3))  # Swap the axes of a specific array.
print(panel4d['A'].swapaxes(0, 1).swapaxes(1, 2).swapaxes(2, 3))  # Swap the axes multiple times.
print(panel4d['A'].transpose())  # Transpose a specific array.
print(panel4d['A'].transpose((1, 0, 2, 3)))  # Transpose a specific array.
print(panel4d['A'].transpose((0, 2, 1, 3)))  # Transpose a specific array.
print(panel4d['A'].transpose((0, 1, 3, 2)))  # Transpose a specific array.
print(panel4d['A'].transpose((2, 1, 0, 3)))  # Transpose a specific array.
print(panel4d['A'].transpose((3, 1, 2, 0)))  # Transpose a specific array.
print(panel4d['A'].transpose((0, 3, 2, 1)))  # Transpose a specific array.
print(panel4d['A'].transpose((1, 0, 2, 3)).transpose((0, 2, 1, 3)).transpose((0, 1, 3, 2)))  # Transpose multiple times.
print(panel4d['A'].T)  # Transpose a specific array.
print(panel4d['A'].T.T)  # Transpose multiple times.
print(panel4d['A'].T.T.T)  # Transpose multiple times.
print(panel4d['A'].T.T.T.T)  # Transpose multiple times.
print(panel4d['A'].T.T.T.T.T)  # Transpose multiple times.
print(panel4d['A'].T.T.T.T.T.T)  # Transpose multiple times.
print(panel4d['A'].T.T.T.T.T.T.T)  # Transpose multiple times.
print(panel4d['A'].T.T.T.T.T.T.T.T)  # Transpose multiple times.
print(panel4d['A'].T.T.T.T.T.T.T.T.T)  # Transpose multiple times.

{'A': array([[[[ 0.68327474,  0.98558258],
         [-0.11809772,  0.80365645]],

        [[ 0.54440516, -1.92974107],
         [ 1.09332335, -0.90874916]]],


       [[[ 1.54312915,  1.3555265 ],
         [ 2.85945488, -0.41522331]],

        [[-0.28912737, -0.36103726],
         [ 1.63643932, -0.72424784]]]]), 'B': array([[[[-0.89578632,  1.64345715],
         [ 0.53406118,  0.10873541]],

        [[-0.07672436, -1.03777627],
         [ 0.71059106,  2.34605273]]],


       [[[-1.95722909, -0.13099851],
         [ 0.5501825 , -0.96549582]],

        [[ 0.41660323, -1.40313257],
         [ 0.57863987,  1.43381529]]]])}
[[[[ 0.68327474  0.98558258]
   [-0.11809772  0.80365645]]

  [[ 0.54440516 -1.92974107]
   [ 1.09332335 -0.90874916]]]


 [[[ 1.54312915  1.3555265 ]
   [ 2.85945488 -0.41522331]]

  [[-0.28912737 -0.36103726]
   [ 1.63643932 -0.72424784]]]]
(2, 2, 2, 2)
4
float64
[[[[ 0.68327474  0.98558258]
   [-0.11809772  0.80365645]]

  [[ 0.54440516 -1.92974107]
   [ 1.09332335 -0