### Advanced Indexing and boolean masking

In [2]:
import numpy as np

In [5]:
data = np.genfromtxt("data.txt", delimiter=",")
print(data)
print(data > 50) # Get a boolean array of the same shape as data, where each element is True if the corresponding element in data is greater than 50, and False otherwise
print(data[data > 50]) # Get a 1D array of all the elements in data that are greater than 50

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[196.  75. 766.  75.  55. 999.  78.  76.  88.]


In [12]:
# We can index with a list in numpy. This is called advanced indexing. It allows us to select specific elements from an array using a list of indices.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[[0, 2, 4, 6, 8]])
np.any(data > 50, axis=0) # Check if any element in data is greater than 50
np.all(data > 50, axis=0) # Check if all elements in data are greater than 50
(data > 50) & (data < 100) # Get a boolean array where each element is True if the corresponding element in data is greater than 50 and less than 100, and False otherwise
(~((data > 50) & (data < 100))) # Get a boolean array where each element is True if the corresponding element in data is not greater than 50 or not less than 100, and False otherwise

[1 3 5 7 9]


array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

### Simple Challange - Advanced Indexing

In [20]:
a = np.arange(1, 31).reshape(6, 5)
print(a)

print(a[2:4, 0:2])
print(a[[0, 1, 2, 3], [1, 2, 3, 4]])
print(a[[0, 4, 5], 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
