## Reorganizing Arrays

In [1]:
import numpy as np

In [3]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
after = before.reshape(8, 1) # Reshape the array to 8 rows and 1 column
print(after)
after = before.reshape(2, 2, 2) # Reshape the array to 2 blocks, 2 rows and 4 columns
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Vectors - Vertical stacking and Horizontal stacking

In [7]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(v1)
print(v2)
stacked = np.stack((v1, v2), axis=0) # Stack the arrays vertically (row-wise)
print(stacked)
stacked = np.stack((v1, v2), axis=1) # Stack the arrays horizontally (column-wise)
print(stacked)
print(np.vstack([v1, v2, v1, v2])) # Stack the arrays vertically (row-wise)
print(np.hstack([v1, v2, v1, v2])) # Stack the arrays horizontally (column-wise)

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
