# Numpy Overview


Numpy is primarily used for numerical operations on arrays. NumPy is essential for data science and scientific computing because it provides tools for handling large datasets efficiently. It is widely used in various fields such as machine learning, data analysis, and engineering.

- **Multi-dimensional arrays**: `ndarray` encapsulates n-dimensional arrays of homogeneous data types. It allows efficient storage and manipulation of large data sets.
- **Performance**: Numpy arrays uses fixed types and are **more efficient than Python lists** because they are stored in contiguous memory locations, which allows for faster access and manipulation. This is known as **locality of reference**.
- **Mathematical Functions**: NumPy provides a wide range of mathematical functions, including operations for *linear algebra, Fourier transforms, and random number generation*.
- **Vectorization and Broadcasting**: NumPy supports vectorized operations, which means that operations are applied element-wise without the need for explicit loops. Broadcasting allows for operations on arrays of different shapes, making the code more concise and readable.


In [37]:
import numpy as np

## Basics

In [38]:
# 1D array
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [39]:
# 2D array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [40]:
# Get Dimension of an array
print('One dimensional array: ', a.ndim)
print('Two dimensional array: ', b.ndim)

One dimensional array:  1
Two dimensional array:  2


In [41]:
# Get Shape of an array
print('Shape of one dimensional array (1 row + 3 columns): ', a.shape)
print('Shape of two dimensional array (2 rows + 3 columns): ', b.shape)

Shape of one dimensional array (1 row + 3 columns):  (3,)
Shape of two dimensional array (2 rows + 3 columns):  (2, 3)


In [42]:
# Get data type of an array
c = np.array([1, 2, 3, 4, 5, 6], dtype='int8') # We can specify the data type of an array
print(c.dtype)
print(f'a data type: {a.dtype}, b data type: {b.dtype}, c data type: {c.dtype}') # or print(a.dtype)

int8
a data type: int64, b data type: float64, c data type: int8


In [45]:
# Get size of an array
print('a - Size of one dimensional array: ', a.itemsize)
print('b - Size of two dimensional array: ', b.itemsize)
print('c - Size of one dimensional array: ', c.itemsize)
c = np.array([1, 2, 3, 4], dtype='int32')
print("c - Resized size of one dimensional array: ", c.itemsize)
# Total size of an array
print('a - Total size of one dimensional array: ', a.size)
print('b - Total size of two dimensional array: ', b.size)
print('c - Total size of one dimensional array: ', c.size)
# Total size of an array in bytes
print('a - Total size of one dimensional array in bytes (a.itemsize * a.size): ', a.nbytes)
print('b - Total size of two dimensional array in bytes (b.itemsize * b.size): ', b.nbytes)
print('c - Total size of one dimensional array in bytes (c.itemsize * c.size): ', c.nbytes)

a - Size of one dimensional array:  8
b - Size of two dimensional array:  8
c - Size of one dimensional array:  4
c - Resized size of one dimensional array:  4
a - Total size of one dimensional array:  3
b - Total size of two dimensional array:  6
c - Total size of one dimensional array:  4
a - Total size of one dimensional array in bytes (a.itemsize * a.size):  24
b - Total size of two dimensional array in bytes (b.itemsize * b.size):  48
c - Total size of one dimensional array in bytes (c.itemsize * c.size):  16
