# Numpy Overview


Numpy is primarily used for numerical operations on arrays. NumPy is essential for data science and scientific computing because it provides tools for handling large datasets efficiently. It is widely used in various fields such as machine learning, data analysis, and engineering.

- **Multi-dimensional arrays**: `ndarray` encapsulates n-dimensional arrays of homogeneous data types. It allows efficient storage and manipulation of large data sets.
- **Performance**: Numpy arrays uses fixed types and are **more efficient than Python lists** because they are stored in contiguous memory locations, which allows for faster access and manipulation. This is known as **locality of reference**.
- **Mathematical Functions**: NumPy provides a wide range of mathematical functions, including operations for *linear algebra, Fourier transforms, and random number generation*.
- **Vectorization and Broadcasting**: NumPy supports vectorized operations, which means that operations are applied element-wise without the need for explicit loops. Broadcasting allows for operations on arrays of different shapes, making the code more concise and readable.


In [2]:
import numpy as np

## Basics

In [3]:
# 1D array
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [4]:
# 2D array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension of an array
print('One dimensional array: ', a.ndim)
print('Two dimensional array: ', b.ndim)

One dimensional array:  1
Two dimensional array:  2


In [6]:
# Get Shape of an array
print('Shape of one dimensional array (1 row + 3 columns): ', a.shape)
print('Shape of two dimensional array (2 rows + 3 columns): ', b.shape)

Shape of one dimensional array (1 row + 3 columns):  (3,)
Shape of two dimensional array (2 rows + 3 columns):  (2, 3)


In [7]:
# Get data type of an array
c = np.array([1, 2, 3, 4, 5, 6], dtype='int8') # We can specify the data type of an array
print(c.dtype)
print(f'a data type: {a.dtype}, b data type: {b.dtype}, c data type: {c.dtype}') # or print(a.dtype)

int8
a data type: int64, b data type: float64, c data type: int8


In [8]:
# Get size of an array
print('a - Size of one dimensional array: ', a.itemsize)
print('b - Size of two dimensional array: ', b.itemsize)
print('c - Size of one dimensional array: ', c.itemsize)
c = np.array([1, 2, 3, 4], dtype='int32')
print("c - Resized size of one dimensional array: ", c.itemsize)
# Total size of an array
print('a - Total size of one dimensional array: ', a.size)
print('b - Total size of two dimensional array: ', b.size)
print('c - Total size of one dimensional array: ', c.size)
# Total size of an array in bytes
print('a - Total size of one dimensional array in bytes (a.itemsize * a.size): ', a.nbytes)
print('b - Total size of two dimensional array in bytes (b.itemsize * b.size): ', b.nbytes)
print('c - Total size of one dimensional array in bytes (c.itemsize * c.size): ', c.nbytes)

a - Size of one dimensional array:  8
b - Size of two dimensional array:  8
c - Size of one dimensional array:  1
c - Resized size of one dimensional array:  4
a - Total size of one dimensional array:  3
b - Total size of two dimensional array:  6
c - Total size of one dimensional array:  4
a - Total size of one dimensional array in bytes (a.itemsize * a.size):  24
b - Total size of two dimensional array in bytes (b.itemsize * b.size):  48
c - Total size of one dimensional array in bytes (c.itemsize * c.size):  16


### Initializing different types of arrays

In [9]:
print(np.zeros(5)) # Create an array of zeros with 5 elements
print(np.zeros((2, 3))) # Create a 2D array of zeros with 2 rows and 3 columns
print(np.zeros((2, 3), dtype='int16')) # Create a 2D array of zeros with 2 rows and 3 columns and specify the data type as int16
print(np.zeros((2, 3, 4, 5))) # Create a 4D array of zeros with 2 blocks, 3 rows, 4 columns, and 5 depth
print(np.ones((2, 3))) # Create a 2D array of ones with 2 rows and 3 columns
print(np.full((2, 3), 7)) # Create a 2D array of sevens with 2 rows and 3 columns
print(np.random.rand(2, 3)) # Create a 2D array of random numbers between 0 and 1 with 2 rows and 3 columns
print(np.random.random_sample((2, 3))) # Create a 2D array of random numbers between 0 and 1 with 2 rows and 3 columns
print(np.random.random_sample(a.shape)) # Create an array of random numbers between 0 and 1 with the same shape as array a
print(np.random.randint(0, 10, (2, 3))) # Create a 2D array of random integers between 0 and 10 with 2 rows and 3 columns
print(np.full_like(a, 4)) # Create an array of fours with the same shape and data type as array a
print(np.identity(5)) # Create a 5x5 identity matrix


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[0.78408749 0.8950438  0.85368601]
 [0.12140043 0.29076174 0.01962227]]
[[0.31046048 0.00506718 0.10978296]
 [0.72052966 0.23467317 0.54445426]]
[0.86147471 0.49351755 0.93716537]
[[9 6 7]
 [1 7 0]]
[4 4 4]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
### Repeating arrays
ar = np.repeat(3, 5) # Create an array of 5 threes
print(ar)
ar = np.repeat([1, 2, 3], 3) # Create an array of 1, 2, and 3 repeated 3 times each
print(ar)
ar = np.repeat([[1, 2, 3]], 3, axis=0) # Create a 2D array of 1, 2, and 3 repeated 3 times each along the rows (axis=0)
print(ar)
ar = np.repeat([[1, 2, 3]], 3, axis=1) # Create a 2D array of 1, 2, and 3 repeated 3 times each along the columns (axis=1)
print(ar)

[3 3 3 3 3]
[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [15]:
# Simple challenge - Solution
output = np.ones((5, 5))
print(output)
z = np.zeros((3, 3))
z[1, 1] = 9
print(z)
output[1:4, 1:4] = z
print(output)
# or
output[1:-1, 1:-1] = z
print(output)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying Arrays

**Note: Becareful when copying arrays**

In [17]:
# Because When Copying Arrays!!!!
a = np.array([1, 2, 3])
b = a # This does not create a new array, it creates a reference to the same array in memory
print('a: ', a)
print('b: ', b)
b[0] = 100 # This changes the value of the first element of the array
print('a: ', a) # This also changes the value of the first element of the array because a and b are referencing the same array in memory
print('b: ', b)
# To create a copy of an array, we can use the copy() method
c = a.copy() # This creates a new array in memory that is a copy of the array a
print('a: ', a)
print('c: ', c)
c[0] = 200 # This changes the value of the first element of the array
print('a: ', a) # This does not change the value of the first element of the array because a and c are referencing different arrays in memory
print('c: ', c)


a:  [1 2 3]
b:  [1 2 3]
a:  [100   2   3]
b:  [100   2   3]
a:  [100   2   3]
c:  [100   2   3]
a:  [100   2   3]
c:  [200   2   3]
