### Accessing Elements, Rows, Columns

In [2]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]) # 2D array
print(a)
print('Shape of the array: ', a.shape) # (2, 7) -> 2 rows and 7 columns
print('Number of dimensions: ', a.ndim) # 2
print('Data type of the array: ', a.dtype) # int64
print('Size of the array: ', a.size) # 14 (total number of elements in the array)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Shape of the array:  (2, 7)
Number of dimensions:  2
Data type of the array:  int64
Size of the array:  14


In [11]:
# Get a specific element of an array [r, c] -> r: row index, c: column index
print('Element at row 0 and column 0: ', a[0, 0]) # 1
print('Element at row 0 and column 1: ', a[0, 1]) # 2
print('Element at row 1 and column 0: ', a[1, 0]) # 8
print('Element at row 1 and column 1: ', a[1, 1]) # 9
print(a[1, 5])
print(a[1, -2]) # Negative indexing -> -1 is the last element, -2 is the second last element, and so on.

Element at row 0 and column 0:  1
Element at row 0 and column 1:  2
Element at row 1 and column 0:  8
Element at row 1 and column 1:  9
13
13


In [13]:
# Get a specific row of an array
print('Row 0: ', a[0])
print('Row 0: ', a[0, :]) # We can also use slicing to get a specific row of an array
# Get a specific column of an array
print('Column 2: ', a[:, 2])

Row 0:  [1 2 3 4 5 6 7]
Row 0:  [1 2 3 4 5 6 7]
Column 2:  [ 3 10]


In [18]:
# Getting [startindex:endindex:step] 
# -> startindex is the index of the first element to be included in the slice, 
# endindex is the index of the first element to be excluded from the slice, 
# and step is the number of indices to skip between elements in the slice. 
# If startindex is omitted, it defaults to 0. If endindex is omitted, 
# it defaults to the length of the array. If step is omitted, it defaults to 1.
print('Elements from index 0 to 5: ', a[0, 1:6:2])
print(a[0, 1:-1:2])

Elements from index 0 to 5:  [2 4 6]
[2 4 6]


In [23]:
# Change the value of a specific element in an array
a[1, 5] = 20
print(a)
# Change entire column of an array
a[:, 2] = 5
print('Changed Entire Column: ', a)
a[:, 2] = [1, 2] # We can also assign a list to change an entire column of an array
print('Changed Column: ', a)
# Change entire row of an array
a[0, :] = 10
print('Changed Entire Row: ', a)

[[10 10 10 10 10 10 10]
 [ 8  9  5 11 12 20 14]]
Changed Entire Column:  [[10 10  5 10 10 10 10]
 [ 8  9  5 11 12 20 14]]
Changed Column:  [[10 10  1 10 10 10 10]
 [ 8  9  2 11 12 20 14]]
Changed Entire Row:  [[10 10 10 10 10 10 10]
 [ 8  9  2 11 12 20 14]]


### 3D Array

In [24]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]]) # 3D array
print(b)
print('Shape of the array: ', b.shape) # (2, 2, 2) -> 2 blocks, 2 rows, and 2 columns
print('Number of dimensions: ', b.ndim) # 3
print('Data type of the array: ', b.dtype) # int64
print('Size of the array: ', b.size) # 8 (total number of elements in the array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of the array:  (2, 2, 2)
Number of dimensions:  3
Data type of the array:  int64
Size of the array:  8


In [26]:
# Get specific element (work outside in)
b[0, 1, 1]
print('Specific element of a 3D array: ', b[0, 1, 1])

Specific element of a 3D array:  4


In [27]:
# Replace specific element of a 3D array
b[:, 1, :] = [[9, 9], [8, 8]]
print('Changed specific element of a 3D array: ', b)

Changed specific element of a 3D array:  [[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
