## Mathematics


In [2]:
import numpy as np

### Arithmetic

In [ ]:
a = np.array([1, 2, 3, 4]) # 1D array
a += 2 # Adding 2 to each element of the array
print(a)
a *= 2 # Multiplying each element of the array by 2
print(a)
a -= 2 # Subtracting 2 from each element of the array
print(a)
a += 6 # Adding 6 to each element of the array
a = a / 2 # Dividing each element of the array by 2
print(a)
a **= 2 # Squaring each element of the array
print(a)
# Take sine of each element of the array
print(np.sin(a))
# Take cosine of each element of the array
print(np.cos(a))    
# Take square root of each element of the array
print(np.sqrt(a))

[3 4 5 6]
[ 6  8 10 12]
[ 4  6  8 10]
[5. 6. 7. 8.]
[25. 36. 49. 64.]
[-0.13235175 -0.99177885 -0.95375265  0.92002604]
[ 0.99120281 -0.12796369  0.30059254  0.39185723]
[5. 6. 7. 8.]


### Linear Algebra

- Determinant
- Trace
- Singular vector Decomposition
- Eigenvalues and Eigenvectors
- Matrix norm
- Inverse

etc..

In [16]:
a = np.ones((2, 3)) # 2D array with 2 rows and 3 columns, filled with ones
print(a)
b = np.full((3, 2), 2) # 2D array with 3 rows and 2 columns, filled with twos
print(b)
c = np.matmul(a, b) # Matrix multiplication of a and b
print(c)
c = np.identity(3) # Identity matrix of size 3x3
print(c)
det = np.linalg.det(c) # Determinant of the identity matrix
print(det)
tr = np.trace(c) # Trace of the identity matrix
print(tr)
svd = np.linalg.svd(c) # Singular Value Decomposition of the identity matrix
print(svd)
egval = np.linalg.eigvals(c) # Eigenvalues of the identity matrix
print(egval)
egvec = np.linalg.eig(c) # Eigenvalues and eigenvectors of the identity matrix
print(egvec)
mtrx_norm = np.linalg.norm(c) # Frobenius norm of the identity matrix
print(mtrx_norm)
inv = np.linalg.inv(c) # Inverse of the identity matrix
print(inv)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0
3.0
SVDResult(U=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), S=array([1., 1., 1.]), Vh=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))
[1. 1. 1.]
EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))
1.7320508075688772
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Statistics

In [19]:
stats = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array with 2 rows and 3 columns
print(stats)
print('Minimum value: ', np.min(stats)) # Minimum value in the array np.min(stats)
print('Minimum value of each column: ', np.min(stats, axis=0)) # Minimum value of each column
print('Minimum value of each row: ', np.min(stats, axis=1)) # Minimum value of each row
print('Maximum value: ', np.max(stats)) # Maximum value in the array np.max(stats)
print('Maximum value of each column: ', np.max(stats, axis=0)) # Maximum value of each column
print('Maximum value of each row: ', np.max(stats, axis=1)) # Maximum value of each row
print('Sum of each column: ', np.sum(stats, axis=0)) # Sum of each column
print('Sum of each row: ', np.sum(stats, axis=1)) # Sum of each row
print('Mean of each column: ', np.mean(stats, axis=0)) # Mean of each column
print('Mean of each row: ', np.mean(stats, axis=1)) # Mean of each row
print('Overall mean: ', np.mean(stats)) # Overall mean
print('Standard deviation of each column: ', np.std(stats, axis=0)) # Standard deviation of each column
print('Standard deviation of each row: ', np.std(stats, axis=1)) # Standard deviation of each row
print('Overall standard deviation: ', np.std(stats)) # Overall standard deviation
print('Variance of each column: ', np.var(stats, axis=0)) # Variance of each column
print('Variance of each row: ', np.var(stats, axis=1)) # Variance of each row
print('Overall variance: ', np.var(stats)) # Overall variance

[[1 2 3]
 [4 5 6]]
Minimum value:  1
Minimum value of each column:  [1 2 3]
Minimum value of each row:  [1 4]
Maximum value:  6
Maximum value of each column:  [4 5 6]
Maximum value of each row:  [3 6]
Sum of each column:  [5 7 9]
Sum of each row:  [ 6 15]
Mean of each column:  [2.5 3.5 4.5]
Mean of each row:  [2. 5.]
Overall mean:  3.5
Standard deviation of each column:  [1.5 1.5 1.5]
Standard deviation of each row:  [0.81649658 0.81649658]
Overall standard deviation:  1.707825127659933
Variance of each column:  [2.25 2.25 2.25]
Variance of each row:  [0.66666667 0.66666667]
Overall variance:  2.9166666666666665
